[r00014.1] Update poky.git : ac4d3fc
git-reposnap-release_tag: r00014.1
git-reposnap-name: external/yoctoproject.org/poky
git-reposnap-prefix: poky
git-reposnap-fetch_url: git://codeaurora.org/quic/ype/external/yoctoproject.org/poky.git
git-reposnap-upstream: refs/heads/yocto/jethro
git-reposnap-rev: ac4d3fca189c8b6b54647ccfca37c812aad98149

commit ac4d3fca189c8b6b54647ccfca37c812aad98149
Author: Andre Rosa <andre.rosa@lge.com>
Date:   Fri Nov 3 12:40:14 2017 +0100

    bitbake: Replace deprecated git branch parameter "--set-upstream"

    Since 2017-08-17 (git version 2.14.1.473.g3ec7d702a) using deprecated
    git branch parameter "--set-upstream" causes a fetcher error. Replace
    it by "--set-upstream-to".

    https://git.kernel.org/pub/scm/git/git.git/commit/?id=52668846ea2d41ffbd87cda7cb8e492dea9f2c4d
    says, it's deprecated since 2012-08-30 so hopefully all still supported
    host distributions have new enough git to support "--set-upstream-to".

    ERROR: PACKAGE do_unpack: Fetcher failure: ...;
    git -c core.fsyncobjectfiles=0 branch --set-upstream master origin/master failed with exit code 128, output:
    fatal: the '--set-upstream' option is no longer supported. Please use '--track' or '--set-upstream-to' instead.

    ERROR: PACKAGE do_unpack: Function failed: base_do_unpack

    (Bitbake rev: 68d061d2517f1a79dc6b14a373ed2dcb78a901ce)

    Signed-off-by: Andre Rosa <andre.rosa@lge.com>
    Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
    Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
    (cherry picked from commit 2ab50074c1a6c56a8a178755de108447d7b7acaf)
    Signed-off-by: Javier Viguera <javier.viguera@digi.com>
    Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>